### ISSUE TITLE
why linux-ayufan?

### ISSUE THREAD

**Issue by bernardoaraujor** [trecetp/meta-rock64#3]
@trecetp why did you decide to set
```
PREFERRED_PROVIDER_virtual/kernel = "linux-ayufan"
```
on `rock64.conf`?

Wouldn't `linux-rockchip.bb` pointing to [github.com/rockchip-linux/kernel](https://github.com/rockchip-linux/kernel) make more sense for a general purpose BSP?

If you're open to the idea, I could try to submit a PR soon.

**Comment by LE0xUL** [comment]
Because the rockchip-linux/kernel is more generic, and the linux-ayufan is tunned specificaly to Rock64
